name = "StaticMPI"
uuid = "20d4277e-fd01-4864-93be-4ec87eb9404e"
authors = ["C. Brenhin Keller"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
