name = "StaticMPI"
uuid = "20d4277e-fd01-4864-93be-4ec87eb9404e"
authors = ["C. Brenhin Keller"]
version = "0.2.1"

[deps]
StaticTools = "86c06d3c-3f03-46de-9781-57580aa96d0a"

[compat]
julia = "1.7"
StaticTools = "0.6.1"
